=== MIND-Tools/web/common/dtd/ow2.dtd
<!-- ============================================================= -->
<!--                    ObjectWeb DTD                              -->
<!-- ============================================================= -->

<!ENTITY % common.markup                                             
                    "code|u|em|strong|sub|sup|a|connect|anchor|img|br" >

<!ENTITY % lists
                       "ul|ol"                                       >

<!ENTITY % blocks.markup
                       "p|copyright|source|%lists;|table|form|script"       >

<!ENTITY % form.markup
                       "input|textarea|select"                       >

<!-- ============================================================= -->
<!--                    Document                                   -->
<!-- ============================================================= -->

<!ELEMENT  document     (properties, body)                           >

<!-- ============================================================= -->
<!--                    Properties                                 -->
<!-- ============================================================= -->

<!ELEMENT  properties   (author+, title, filename, pathtoroot)       >

<!--                    Document author                            -->
<!ELEMENT  author       (#PCDATA)                                    >
<!ATTLIST  author
             email      CDATA                              #REQUIRED >

<!--                    Document title                             -->
<!ELEMENT  title        (#PCDATA)                                    >

<!--                    Filename (used for intern purpose)         -->
<!ELEMENT  filename     (#PCDATA)                                    >

<!--                    Path to root project (used for intern purpose) -->
<!ELEMENT  pathtoroot   (#PCDATA)                                    >

<!-- ============================================================= -->
<!--                    Body                                       -->
<!-- ============================================================= -->

<!ELEMENT  body         (s1+)                                        >

<!--                    Section                                    -->
<!ELEMENT  s1           (%blocks.markup;|s2|subtitle|hr)*            >
<!ATTLIST  s1
             name       CDATA                              #REQUIRED
             anchor     CDATA                              #IMPLIED  >

<!--                    Subsection                                 -->
<!ELEMENT  s2           (%blocks.markup;|subtitle|hr)*               >
<!ATTLIST  s2
             name       CDATA                              #REQUIRED
             anchor     CDATA                              #IMPLIED  >

<!--                    Subtitle                                   -->
<!ELEMENT  subtitle     (#PCDATA|a|connect)*                         >
<!ATTLIST  subtitle
             anchor     CDATA                              #IMPLIED  >

<!-- ============================================================= -->
<!--                    block markup                               -->
<!-- ============================================================= -->

<!--                    Text Paragraph                             -->
<!ELEMENT  p            (#PCDATA | %common.markup;)*                 >

<!--                    Source Paragraph                           -->
<!ELEMENT  source       (#PCDATA)                                    >

<!--                    Copyright disclaimer                       -->
<!ELEMENT  copyright    (#PCDATA|br)*                                >


<!-- ============================================================= -->
<!--                    Table                                      -->

<!--                    Attributes that indicate the spanning and
                        the align of the table cell                -->
<!ENTITY % cell.span   
                        'colspan CDATA "1" rowspan CDATA "1"'        >
<!ENTITY % cell.align  
 'align (left|center|right) "left" valign (top|middle|bottom) "top"' >

<!--                    Table element                              -->
<!ELEMENT  table        (tr+)                                        >
<!ATTLIST  table
            border      CDATA                              '1'
            width       CDATA                              #IMPLIED >

<!--                    Table row header element                   -->
<!ELEMENT  th           (#PCDATA)                                    >
<!ATTLIST  th
            %cell.span;
            %cell.align;                                             >

<!--                    Table row element                          -->
<!ELEMENT  tr           (th|td)+                                     >

<!--                    Table row description element              -->
<!ELEMENT  td           (#PCDATA|%common.markup;|%lists;|%form.markup;|p|hr)* >
<!ATTLIST  td
            %cell.span;                                              
            %cell.align;                                             >

<!-- ============================================================= -->
<!--                    Lists                                      -->

<!--                    Unordered list (typically bulleted)        -->
<!ELEMENT ul            (li, (li | %lists;)*)                        >

<!--                    Ordered list (typically numbered)          -->
<!ELEMENT ol            (li, (li | %lists;)*)                        >

<!--                    List item                                  -->
<!ELEMENT li            (#PCDATA|%common.markup;|%blocks.markup;)*    >

<!-- ============================================================= -->
<!--                    Common markup                              -->
<!-- ============================================================= -->

<!--                    Code (typically monospaced)                -->
<!ELEMENT  code         (#PCDATA)                                    >

<!ELEMENT  u            (#PCDATA)                                    >

<!--                    Emphasis (typically italic)                -->
<!ELEMENT  em           (#PCDATA|code|sup|sub|a|connect)*            >

<!--                    Strong (typically bold)                    -->
<!ELEMENT  strong       (#PCDATA|code|sup|sub|a|connect|br)*         >

<!--                    Superscript (typically smaller and higher) -->
<!ELEMENT  sup          (#PCDATA)                                    >

<!--                    Subscript (typically smaller and lower)    -->
<!ELEMENT  sub          (#PCDATA)                                    >

<!--                    Image                                      -->
<!ELEMENT  img          EMPTY                                        >
<!ATTLIST  img
             src        CDATA                              #REQUIRED
             alt        CDATA                              #REQUIRED
             border     CDATA                              #REQUIRED
             height     CDATA                              #REQUIRED
             width      CDATA                              #REQUIRED
             hspace     CDATA                              #IMPLIED 
             vspace     CDATA                              #IMPLIED 
             align      (top|middle|bottom)                "middle"  >

<!--                    horizontal rule                            -->
<!ELEMENT  hr           EMPTY                                        >

<!--                    forced line break                          -->
<!ELEMENT  br           EMPTY                                        >

<!-- ============================================================= -->
<!--                    Links                                      -->

<!--                    Hard replacing link (equivalent of <a
                        name="">                                   -->
<!ELEMENT  anchor       EMPTY                                        >
<!ATTLIST  anchor
             name       CDATA                              #REQUIRED >

<!--                    Hard replacing link (equivalent of <a ...> -->
<!ELEMENT  a            (#PCDATA|code|sub|sup|img|br)*               >
<!ATTLIST  a
             href       CDATA                              #REQUIRED
             fork       (false|true)                       "false"   >

<!--                    Soft link between processed pages (no
                        equivalent in HTML)                        -->
<!ELEMENT  connect      (#PCDATA|code|sub|sup|img)*                  >
<!ATTLIST  connect
             href       CDATA                              #REQUIRED >

<!-- ============================================================= -->
<!--                    form                                       -->
<!-- ============================================================= -->

<!ELEMENT  form        (table|%form.markup;|subtitle|p|hr)+          >
<!ATTLIST  form
             method     (get|post)                         "post"      
             action     CDATA                              #REQUIRED >


<!ELEMENT  input        EMPTY                                        >
<!ATTLIST  input
             type   (text|hidden|checkbox|radio|submit|reset)  #REQUIRED
             name       CDATA                              #REQUIRED  
             value      CDATA                              #REQUIRED  
             size       CDATA                              #IMPLIED  
             checked    (checked)                          #IMPLIED  >

<!ELEMENT  textarea     (#PCDATA)                                    >
<!ATTLIST  textarea
             name       CDATA                              #REQUIRED
             rows       CDATA                              #IMPLIED   
             cols       CDATA                              #IMPLIED  >

<!ELEMENT  select       (option+)                                    >
<!ATTLIST  select
             name       CDATA                              #REQUIRED      
             size       CDATA                              #REQUIRED >

<!ELEMENT  option       (#PCDATA)                                    >
<!ATTLIST  option
             value      CDATA                              #IMPLIED  
          selected      (selected)                         #IMPLIED  >

<!-- ============================================================= -->
<!--                    script                                     -->
<!-- ============================================================= -->

<!--                    Script                                     -->
<!ELEMENT  script       EMPTY                                        >
<!ATTLIST  script
             type       CDATA                              #REQUIRED
             src        CDATA                              #REQUIRED >
<!-- ============================================================= -->
<!--                    end of DTD                                 -->
<!-- ============================================================= -->

=== MIND-Tools/web/xml/root/index.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!DOCTYPE document SYSTEM '../../common/dtd/ow2.dtd'>

<document>
  <properties>
    <author email="mind@ow2.org">MIND team</author>
    <title>Home Page</title>
    <filename>index.xml</filename>
    <pathtoroot>.</pathtoroot>
  </properties>

  <body>
    <s1 name="The MIND Project">

      <s2 name="News">

        <p>
          20/01/10 : The MIND OW2 project is now available !
        </p>

      </s2>

      <s2 name="Project Description">

        <p>
          <strong>
            MIND is an implementation of the
            <a href="http://fractal.ow2.org">Fractal</a>
            component model for the development of embedded softwares
          </strong>
          It provides an architecture compilation tool-chain, a component
          library and an integrated development environment based on Eclipse.
        </p>

      </s2>

      <hr />

    </s1>

  </body>
</document>

=== MIND-Tools/web/xml/root/team.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!DOCTYPE document SYSTEM '../../common/dtd/ow2.dtd'>

<document>
  <properties>
    <author email="mind@ow2.org">MIND team</author>
    <title>Team</title>
    <filename>team.xml</filename>
    <pathtoroot>.</pathtoroot>
  </properties>

  <body>
    <s1 name="MIND Team">
      <p>The MIND project has been originally developed in the context of the 
        MIND funded project of the French <a href="http://minalogic.org/">Minalogic</a>
        "pole de competitivite". Partners of this funded project are :</p>
      
      <ul>
        <li><a href="http://www.st.com">STMicroelectronics</a></li>
        <li><a href="http://www.stericsson.com">STErcisson</a></li>
        <li><a href="http://www.rd.francetelecom.com">France Telecom R&amp;D</a></li>
        <li><a href="http://www.schneider-electric.fr">Schneider Electric</a></li>
        <li><a href="http://www.logica.fr">Logica</a></li>
        <li><a href="http://www.fr.sogeti.com">Sogeti</a></li>
        <li><a href="http://www.groupe-open.com/">Groupe OPEN</a></li>
        <li><a href="http://www.itlabs.fr.orange-business.com/">IT&amp;Labs</a></li>
        <li><a href="http://www.itris.fr/">Itris Automation Square</a></li>
        <li><a href="http://www.is2t.com/">IS2T</a></li>
        <li><a href="http://www.inria.fr">INRIA</a> (<a href="http://sardes.inrialpes.fr">Sardes</a>
           and <a href="http://adam.lille.inria.fr">ADAM</a> teams)</li>
        <li><a href="http://www-list.cea.fr/">CEA LIST</a></li>
        <li><a href="http://www.liglab.fr/">LIG</a> (<a href="http://www-adele.imag.fr/">ADELE team</a>)</li>
        <li><a href="http://www.ineris.fr/">INERIS</a></li>
        <li><a href="http://www.istia.univ-angers.fr/">ISTIA</a></li>
      </ul>
        
    </s1>

  </body>
</document>

=== MIND-Tools/web/xml/root/license.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!DOCTYPE document SYSTEM '../../common/dtd/ow2.dtd'>

<document>
  <properties>
    <author email="mind@ow2.org">MIND team</author>
    <title>License Status</title>
    <filename>license.xml</filename>
    <pathtoroot>.</pathtoroot>
  </properties>

  <body>
    <s1 name="License Status">
      <p>The mindc tool-chain, the component library and the IDE are licensed 
        under the <a href="http://www.gnu.org/copyleft/lesser.html">GNU Lesser
        General Public License</a>.</p>
    </s1>
  </body>
</document>

=== MIND-Tools/web/xml/root/download.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!DOCTYPE document SYSTEM '../../common/dtd/ow2.dtd'>

<document>

  <properties>
    <author email="mind@ow2.org">MIND team</author>
    <title>Download</title>
    <filename>download.xml</filename>
    <pathtoroot>.</pathtoroot>
  </properties>

  <body>
    <s1 name="Getting the tool-chain">
      <p>The mindc tool-chain is available on the 
        <a href="http://forge.ow2.org/project/showfiles.php?group_id=375">MIND Forge</a>
        The tool-chain requires a Java virtual machine and use GCC by default to
        compile C files.</p>
    </s1>

    <s1 name="Getting the sources">
      <p>You can visit the
        <a href="http://forge.ow2.org/plugins/scmsvn/index.php?group_id=375">MIND SVN page</a>
        for instructions on how to perform a checkout of the sources.</p>

      <p>The mindc tool-chain (in <code>trunk/mind-compiler</code>)is built with
        <a href="http://maven.apache.org/">Maven</a> and is self-contained, 
        which means that you can check it out and build it. See the
         <code>README.txt</code> file for build instructions.</p>
    </s1>
  </body>
</document>

=== MIND-Tools/web/xml/root/documentation.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!DOCTYPE document SYSTEM '../../common/dtd/ow2.dtd'>

<document>
  <properties>
    <author email="mind@ow2.org">MIND team</author>
    <title>Documentation</title>
    <filename>documentation.xml</filename>
    <pathtoroot>.</pathtoroot>
  </properties>

  <body>
    <s1 name="mindc documentation">
      <p><strong>mindc</strong> is a modular and extensible architecture 
        compilation tool-chain that can be used to compile component-based 
        applications from their architectural descriptions (ADL files).
      </p>
      <s2 name="User Guide">
        <p>The <em>mindc User Guide</em> gives a description of:</p>
        <ul>
          <li>the ADL and IDL languages used to describe the architecture of
            an application;</li>
          <li>the coding conventions that must be followed in the C code,</li>
          <li>the use of the mindc tool-chain.</li>
        </ul>
        <p>This document is available in multiple versions:</p>
        <ul>
          <li><a href="mindc/mindc-user-guide.pdf">PDF</a></li>
          <li><a href="mindc/userGuide/mindc-user-guide.html">Multiple HTML pages</a></li>
          <li><a href="mindc/mindc-user-guide.html">Single HTML page</a></li>
          <li><a href="mindc/printable/mindc-user-guide.html">Printable HTML page</a></li>
        </ul>
      </s2>

 	  <s2 name="Technical documentation">
        <p>The <a href="mindc/index.html">mindc Technical documentation</a>
          contains various generated reports based on the mindc source code. It
          includes javadoc, highlighted source-code, test-coverage and various
          maven reports</p>
      </s2>
    </s1>
      
      
      
    <s1 name="MindEd documentation">
		<p><strong>MindEd</strong> is an Eclipse-based IDE (Integrated Development Environment)
		for fractal MIND applications.<br/>
		MindEd provides for ADL, IDL and CPL files :</p>
		<ul>
			<li>a textual editor with auto-completion, syntaxic and semantic coloring, Eclipse's quick-fix system among other features.</li>
			<li>a specialised navigator to handle project exploration, which automatically manages paths and makefile.</li>
			<li>a graphical editor for a visual representation and edition of mind's components.</li>
		</ul>
		
		<!-- Not done yet
		<s2 name="User Guide">
		</s2>
		-->
		<s2 name="Technical documentation">
			<p>MindEd is an Eclipse plug-in created with three modeling frameworks (code generation facilities) developped by the Eclipse Project :</p>
			<ul>
			<li>Eclipse Modeling Framework (EMF) generates a structured data model (more info <a href="http://www.eclipse.org/modeling/emf/">here</a>)</li>
			<li>Textual Modeling Framework (TMF Xtext) generates a text editor based on a given grammar (more info <a href="http://www.eclipse.org/modeling/tmf/?project=xtext">here</a>)</li>
			<li>Graphical Modeling Framework (GMF) generates a graphical editor based on and EMF metamodel, both for edition and visualisation (more info <a href="http://www.eclipse.org/modeling/gmf/">here</a>)</li>
			</ul>
		</s2>
	</s1>

    <s1 name="Reference Documentation">
      <p>The specification of the Fractal component model is presented in the
        <a href="http://fractal.ow2.org/specification/index.html"> The Fractal
        Component Model</a> document.</p>
    </s1>
	
	<s1 anchor="list" name="Mailing List">
      <p>Questions, comments, ideas, etc. related to MIND can be posted on the
        <a href="mailto:mind@objectweb.org">MIND mailing list</a>.</p>
    </s1>
	
	
	
  </body>
</document>
